# Generated by Django 5.1.5 on 2025-02-07 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_lead_score'),
        ('sales', '0003_invoice_newsale_receipt_delete_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('refund_method', models.CharField(choices=[('credit', 'Credit to Account'), ('bank', 'Bank Transfer'), ('cash', 'Cash Refund')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
