# Generated by Django 5.1.5 on 2025-02-09 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_supplier'),
        ('sales', '0004_returnrefund'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsale',
            name='product',
            field=models.ForeignKey(default='viatu', on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsale',
            name='customer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
