# Generated by Django 5.1.5 on 2025-02-09 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_newsale_product_alter_newsale_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsale',
            name='product',
        ),
    ]
