# Generated by Django 5.1.5 on 2025-02-07 10:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=255)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DebtPaymentTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('method', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank'), ('Online', 'Online')], max_length=50)),
                ('debt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='Debts_Management.customerdebt')),
            ],
        ),
        migrations.CreateModel(
            name='DebtReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=50)),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='Debts_Management.customerdebt')),
            ],
        ),
        migrations.CreateModel(
            name='DueDateReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateField()),
                ('reminder_method', models.CharField(choices=[('SMS', 'SMS'), ('Email', 'Email')], max_length=50)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due_date_reminders', to='Debts_Management.customerdebt')),
            ],
        ),
        migrations.CreateModel(
            name='OutstandingBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outstanding_balances', to='Debts_Management.customerdebt')),
            ],
        ),
    ]
