# Generated by Django 5.1.5 on 2025-02-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_category_rename_name_product_product_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(default='mwakalikamo', max_length=255),
            preserve_default=False,
        ),
    ]
