# Generated by Django 5.1.5 on 2025-02-09 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_newsale_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsale',
            name='total_amount',
        ),
    ]
