# Generated by Django 5.1.5 on 2025-02-09 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_newsale_total_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsale',
            old_name='final_amount',
            new_name='total_amount',
        ),
    ]
