# Generated by Django 5.1.5 on 2025-02-10 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_rename_final_amount_newsale_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsale',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Mobile Money', 'Mobile Money'), ('Bank Transfer', 'Bank Transfer')], default='Cash', max_length=50),
        ),
        migrations.AlterField(
            model_name='newsale',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Paid', max_length=50),
        ),
    ]
