# Generated by Django 5.1.5 on 2025-02-11 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Purchases_Expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
    ]
