# Generated by Django 5.1.5 on 2025-02-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_customer_user_customer_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='lead_score',
            field=models.FloatField(default=0.0),
        ),
    ]
